
project_id = "dqfnetchkvnzrtacgvfw"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.course-scraper]

[functions.education-automation]

[functions.generate-certificate]

[functions.generate-course-expiration-notifications]

[functions.select_columns_info]

[functions.send-contact-email]

[functions.send-course-expiration-emails]

[functions.talent-sync]
