
# Project Configuration
project_id = "dqfnetchkvnzrtacgvfw"

[functions.course-scraper]
verify_jwt = true

[functions.send-course-expiration-emails]
verify_jwt = false

[functions.generate-course-expiration-notifications]
verify_jwt = false

[functions.talent-sync]
verify_jwt = true
