
import { Course } from "./courseTypes";

export const sampleCourses: Course[] = [
  {
    id: "1",
    title: "Fashion Design Basics",
    summary: "Learn the basics of fashion design",
    category: "designer",
    level: "beginner",
    duration: "3 hours",
    image_url: "https://example.com/fashion-design.jpg",
    image: "https://example.com/fashion-design.jpg",
    source_url: "https://example.com/fashion",
    content_type: "video",
    career_interests: ["fashion", "design"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "2",
    title: "Advanced Runway Techniques",
    summary: "Master the art of runway modeling",
    category: "model",
    level: "advanced",
    duration: "2 hours",
    image_url: "https://example.com/runway.jpg",
    image: "https://example.com/runway.jpg",
    source_url: "https://example.com/runway",
    content_type: "video",
    career_interests: ["modeling", "fashion"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "3",
    title: "Photography for Beginners",
    summary: "A comprehensive guide to photography",
    category: "photographer",
    level: "beginner",
    duration: "4 hours",
    image_url: "https://example.com/photography.jpg",
    image: "https://example.com/photography.jpg",
    source_url: "https://example.com/photography",
    content_type: "article",
    career_interests: ["photography", "media"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "4",
    title: "Modeling Portfolio Creation",
    summary: "Build your professional modeling portfolio",
    category: "model",
    level: "beginner",
    duration: "1 hour",
    image_url: "https://example.com/portfolio.jpg",
    image: "https://example.com/portfolio.jpg",
    source_url: "https://example.com/portfolio",
    content_type: "guide",
    career_interests: ["modeling", "photography"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "5",
    title: "Video Production Essentials",
    summary: "Learn the fundamentals of video production",
    category: "videographer",
    level: "intermediate",
    duration: "5 hours",
    image_url: "https://example.com/video-production.jpg",
    image: "https://example.com/video-production.jpg",
    source_url: "https://example.com/video",
    content_type: "course",
    career_interests: ["videography", "film"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "6",
    title: "Music Production Basics",
    summary: "Get started with music production",
    category: "musical_artist",
    level: "intermediate",
    duration: "6 hours",
    image_url: "https://example.com/music-production.jpg",
    image: "https://example.com/music-production.jpg",
    source_url: "https://example.com/music",
    content_type: "course",
    career_interests: ["music", "production"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "7",
    title: "Introduction to Painting",
    summary: "Learn painting techniques for beginners",
    category: "fine_artist",
    level: "beginner",
    duration: "3 hours",
    image_url: "https://example.com/painting.jpg",
    image: "https://example.com/painting.jpg",
    source_url: "https://example.com/painting",
    content_type: "tutorial",
    career_interests: ["art", "painting"],
    hosting_type: "hosted",
    is_published: true,
  },
  {
    id: "8",
    title: "Event Planning Masterclass",
    summary: "Comprehensive guide to planning successful events",
    category: "event_planner",
    level: "advanced",
    duration: "8 hours",
    image_url: "https://example.com/event-planning.jpg",
    image: "https://example.com/event-planning.jpg",
    source_url: "https://example.com/events",
    content_type: "course",
    career_interests: ["events", "planning"],
    hosting_type: "hosted",
    is_published: true,
  },
];

export default sampleCourses;
